name: block hunt
author: PhilosophyWithJosh
version: 1.6.0
main: me.PhilosophyWithJosh.blockhunt.Main
description: my take on dreams block hunt
commands:
  beblockhunter:
    description: turns the user into a block hunter
  leaveblockhunt:
    description: leaves the blockhunt
  startblockhunt:
    description: starts the game
